export const FEEDBACK_REQUEST = 'FEEDBACK_REQUEST';
export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
export const FEEDBACK_FAILURE = 'FEEDBACK_FAILURE';
export const FEEDBACK_DETAIL_REQUEST = 'FEEDBACK_DETAIL_REQUEST';
export const FEEDBACK_DETAIL_SUCCESS = 'FEEDBACK_DETAIL_SUCCESS';
export const FEEDBACK_DETAIL_FAILURE = 'FEEDBACK_DETAIL_FAILURE';
