export const SET_SAVED_STUDY_ROOMS = 'SET_SAVED_STUDY_ROOMS';
export const SAVED_STUDY_ROOMS_SUCCESS = 'SAVED_STUDY_ROOMS_SUCCESS';
export const SAVED_STUDY_ROOMS_FAILURE = 'SAVED_STUDY_ROOMS_FAILURE';
