export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const LOG_OUT = 'LOG_OUT';
export const UPDATE_NICKNAME = 'UPDATE_NICKNAME';
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE';
export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE';
