export const SET_VOICE_MODEL = 'SET_VOICE_MODEL';
export const FETCH_VOICE_MODEL_ERROR = 'FETCH_VOICE_MODEL_ERROR';
export const UPLOAD_VOICE_MODEL_SUCCESS = 'UPLOAD_VOICE_MODEL_SUCCESS';
export const UPLOAD_VOICE_MODEL_ERROR = 'UPLOAD_VOICE_MODEL_ERROR';
