OPENVIDU_URL: http://localhost:4443/
server:
  servlet:
    contextPath: /
  address: localhost
  port: '8080'
  ssl:
    enabled: 'false'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  security:
    oauth2:
      client:
        registration:
          google:
            resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
            redirect-uri: http://localhost:5173/auth/google
            token-uri: https://oauth2.googleapis.com/token
            clientId: 880467429579-7jotat5m39rfgdnrnpleinfijd0pf5c9.apps.googleusercontent.com
            clientSecret: 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
  redis:
    host: localhost
    port: '6379'
  application:
    name: ptpt
  datasource:
    password: '1234'
    username: root
    url: jdbc:mysql://localhost:3306/pt2_db
  devtools:
    livereload:
      enabled: 'true'
  data:
    mongodb:
      uri: mongodb://localhost:27017/pt2_db
OPENVIDU_SECRET: MY_SECRET

rest-api-key: c78c1a46bb34853b94a1b1d4d9f7d9d2
redirect-uri: http://localhost:8080/member/signin/kakao
client-secret:
authorize-uri: https://kauth.kakao.com/oauth/authorize
token-uri: https://kauth.kakao.com/oauth/token
kakao-api-host: https://kapi.kakao.com